/**
 * PANDA 3D SOFTWARE
 * Copyright (c) Carnegie Mellon University.  All rights reserved.
 *
 * All use of this software is subject to the terms of the revised BSD
 * license.  You should have received a copy of this license along
 * with this source code in a file named "LICENSE."
 *
 * @file modelIndexToBoo.h
 * @author lachbr
 * @date 2021-03-05
 */

#ifndef MODELINDEXTOBOO_H
#define MODELINDEXTOBOO_H

#include "programBase.h"
#include "withOutputFile.h"

/**
 * Tiny little program that compiles the model tree index file, generated by
 * ppremake, into a binary format that is quick for the tools to load up.
 */
class ModelIndexToBoo : public ProgramBase, public WithOutputFile {
public:
  ModelIndexToBoo();

  void run();

protected:
  virtual bool handle_args(Args &args);

  Filename _input_filename;
};

#endif // MODELINDEXTOBOO_H
